version: 0.0
Resources: 
  - TargetService:
      Type: AWS::ECS:Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:111111111111:task-definition/DemoAppTaskDefinition:15"
        LoadBalancerInfo:
          ContainerName: "DemoAppContainer"
          ContainerPort: 8000

















